version: 3.8

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_database
    ports:
      - '27017:27017'



  nodewebapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_webapo_container
    ports:
        - '3000:3000'
    depends_on:
        - mongodb
    
      

