apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-app
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongo-container-app
          image: mongo:latest

---

apiVersion: v1
kind: Service
metadata:
  name: mongo-service-app
spec:
  selector:
    app: mongodb-app
  ports:
    - name: tcp
      port: 27017
      targetPort: 27017
  